### DISCUSSION TITLE
How to quickly deploy redashcommunity/redash through a Docker image?

### DISCUSSION THREAD

**Discussion by Jengro777** [RedashCommunity/redash#26] [General]
Create two files, docker-compose.yml and env, respectively, under the same directory named redash.

docker-compose.yml:
```
version: "2"
x-redash-service: &redash-service
  image: redashcommunity/redash:preview
  depends_on:
    - postgres
    - redis
  env_file: 
    - ./env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 10

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 10

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 10

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 20

  redis:
    image: redis:6.0.6-alpine
    container_name: redash-redis
    restart: always

  postgres:
    image: postgres:15.3-alpine
    container_name: redash-postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: 
      - ./env
    ports:
      - "5432:5432"
    restart: always

```

env:
> For good security, those values are supposed to be generated by the user and kept secure in that env file.
```
PYTHONUNBUFFERED=0
REDASH_LOG_LEVEL=INFO
REDASH_REDIS_URL=redis://redis:6379/0

REDASH_COOKIE_SECRET=xvyXYDAYgMNB1hbjJPrha95LkeXLArFP
#用于session加密
REDASH_SECRET_KEY=lfLqjWNNetKNU4gb1uTwPxukNPrunuey
#用于数据库字段值加密，例如数据源账户密码
POSTGRES_PASSWORD=wxK3u5spuoqI5gaogYdz0yMTkKtZilYy
REDASH_DATABASE_URL=postgresql://postgres:wxK3u5spuoqI5gaogYdz0yMTkKtZilYy@postgres/postgres
#开启自定义代码
REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS="true"
#开启特殊数据源
REDASH_ADDITIONAL_QUERY_RUNNERS="redash.query_runner.python"
# REDASH_ADDITIONAL_QUERY_RUNNERS="redash.query_runner.oracle,redash.query_runner.python"
```

Execute the following command in the same directory to create the database:

```
docker compose run --rm server create_db
```

In the directory to install Redash, execute the command :
```docker compose up -d```

Open [http://127.0.0.1:5000](http://127.0.0.1:5000) to access Redash.

--------------------------------------------------------------------------------------------------------------------------------------------------------
If this is your first time installing, opening `http://127.0.0.1:5000` will display a prompt:

**Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

This is because the Postgres database has not been created. Execute the following command in the same directory to create the database:

```
docker compose run --rm server create_db
```
--------------------------------------------------------------------------------------------------------------------------------------
redash中文部署以及操作手册
操作手册： https://www.yuque.com/summer-l4v2u/pxnwqp/bqgt5n 
部署文档：https://redash.dazdata.com/docs/opensource/opensouce_install/installer_introduce

**Comment by gaecoli** [comment]
Thank you!

**Comment by justinclift** [comment]
Just to point out, that's what the [`setup.sh`](https://github.com/RedashCommunity/setup/blob/master/setup.sh) script is for.

It's currently designed for Ubuntu though, it won't (yet) work on RHEL/CentOS based systems.

On that note, the version of it [here](https://github.com/justinclift/redash/blob/redash-centos7/setup/setup.sh) was updated to work with CentOS 7 a few years ago.  We could grab the updates from that too, and merge it into our own script.

**Comment by justinclift** [comment]
Btw, if you run the database creation step before the `docker-compose up -d` step:

```
$ docker-compose run --rm server create_db
$ docker-compose up -d
```

... that should avoid the `Internal server error` problem. :smile:

**Comment by justinclift** [comment]
As a 2nd thought, the version of PostgreSQL you have listed is very old, and out of support:

```
image: postgres:9.6-alpine
```

It's safer to move to a newer PostgreSQL.  I know for sure that version 13 of PostgreSQL works well in production with Redash, though both PostgreSQL 14 and 15 are likely fine as well. :smile:

**Reply by gaecoli** [reply]
> As a 2nd thought, the version of PostgreSQL you have listed is very old, and out of support:
> 
> ```
> image: postgres:9.6-alpine
> ```
> 
> It's safer to move to a newer PostgreSQL. I know for sure that version 13 of PostgreSQL works well in production with Redash, though both PostgreSQL 14 and 15 are likely fine as well. 😄

I using pg:12. It's perfect.

**Reply by justinclift** [reply]
Yeah, version 12 will work.  It's "End of Life" is at the end of next year though:

https://www.postgresql.org/support/versioning/

If we use a newer version, then we (and our users) won't need to think about it for a few extra years. :smile:

**Comment by justinclift** [comment]
Btw, displaying hard coded values here is kind of dangerous for anyone that wants to cut-n-paste the above:

```
REDASH_COOKIE_SECRET=xvyXYDAYgMNB1hbjJPrha95LkeXLArFP
REDASH_SECRET_KEY=lfLqjWNNetKNU4gb1uTwPxukNPrunuey
POSTGRES_PASSWORD=wxK3u5spuoqI5gaogYdz0yMTkKtZilYy
REDASH_DATABASE_URL=postgresql://postgres:wxK3u5spuoqI5gaogYdz0yMTkKtZilYy@postgres/postgres
```

For good security, those values are supposed to be generated by the user and kept secure in that file. :smile:

**Reply by Jengro777** [reply]
I have forgotten how to encode, it would be great if the steps to generate the encoding could be written down and placed in the same location so that new students can quickly deploy Redash.

**Reply by Jengro777** [reply]
I will update the above steps based on everyone's suggestions.

**Reply by justinclift** [reply]
Ahhh.  Sorry, I didn't realise you aren't familiar with shell scripts.  That's my bad.

With the shell script used to automatically deploy stuff, it has this:

```
COOKIE_SECRET=$(pwgen -1s 32)
SECRET_KEY=$(pwgen -1s 32)
POSTGRES_PASSWORD=$(pwgen -1s 32)
REDASH_DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgres/postgres"
```

What that is doing is running this three times:

```
$ pwgen -1s 32
```

Each time it runs, it generates a new random string.  That new string then gets stored in one of `COOKIE_SECRET`, `SECRET_KEY`, or `POSTGRES_PASSWORD`.

These are then written to the environment file (`env` above).

Does that make sense?

**Comment by Jengro777** [comment]
Can Redash be deployed with a MySQL 8.0 database backend?

**Reply by gaecoli** [reply]
> Can Redash be deployed with a MySQL 8.0 database backend?

Now, it's just support pg.

**Reply by justinclift** [reply]
No.  MySQL would generally be regarded as a downgrade anyway.

**Comment by tinder-tder** [comment]
sorry I have really been busy with 9-5 job, but we use it with postgres 14.6 (rds) and its working fine, we can update the docker file to use that if not latest or 15.x as the first post

**Comment by Jengro777** [comment]
@justinclift @gaecoli 
Maybe we should take some time to create a Windows installation package for the community edition of Redash. Many novice students or analysts who don't know Docker hope to have a BI tool that can be installed with one click. And Windows has a very high market share. I think it is necessary to create a tool package that can be installed with one click on Windows.

refer to:  https://redash.dazdata.com/docs/download/opensource

**Reply by Adityak4201** [reply]
I was facing issue while starting postgres:15.3-alpine in Ubuntu 20.04 in redash. I was getting the below error:

`chown: changing ownership of ‘/var/lib/postgresql/data’: Operation not permitted`

I fixed the issue by adding the following variables in the env file:

```PGDATA=/var/lib/postgresql/data/pgdata```

Please add this in the above documentation.

**Comment by Adityak4201** [comment]
I was facing issue while starting postgres:15.3-alpine in Ubuntu 20.04 in redash. I was getting the below error:

`chown: changing ownership of ‘/var/lib/postgresql/data’: Operation not permitted`

I fixed the issue by adding the following variables in the env file:

```
PGDATA=/var/lib/postgresql/data/pgdata
```

Please add this in the above documentation.

**Reply by justinclift** [reply]
> PGDATA=/var/lib/postgresql/data/pgdata

That "pgdata" string on the end doesn't sound right.

At a guess, this is probably something to do with permissions of the `/var/lib/postgresql/data` directory, and the extra directory name after it might be working around the problem.  That's just a first guess though. :smile:

**Reply by Adityak4201** [reply]
Yes, it was a permission problem. postgresql mounts files on the machine by its own custom user (UID: 70) as visible in their [Dockerfile](https://github.com/docker-library/postgres/blob/5ea98fe00be95fbbe642732d62af3b4dbc83f442/15/alpine3.18/Dockerfile). 

However, according to redash community docker-compose.yml, this mounted data is kept in the same directory as docker-compose.yml.

```
  postgres:
    image: postgres:15.3-alpine
    container_name: redash-postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
```

After the postgresql files have been mounted in the directory, they are to be mount on the `/var/lib/postgresql/data` folder. But the user (UID: 70 for postgresql) who added the postgres-data, is not present anymore in the system (`/etc/passwd` file in linux). That is why, the problem was occuring where the postgres-data folder was not mounted in `/var/lib/postgresql/data` folder.

I read their [documentation](https://hub.docker.com/_/postgres) and found that PGDATA variable solves this problem.
