### ISSUE TITLE
When will the new community edition Docker image be released?

### ISSUE THREAD

**Issue by Avey777** [RedashCommunity/redash#15]
We have a small frontend modification that needs to be released in the new community version, but we've been stuck on Python package dependencies for the backend environment. Now we've successfully developed the feature we need through the API preview, but we want to contribute it to the new Redash community and hope that it can be included in the next Docker image release.

**Comment by gaecoli** [comment]
> 

你卡在Python构建的哪一步了？有没有截图发出来？

**Comment by Avey777** [comment]
Which version of Python should I use? 
I am currently using Python 3.9, but it seems that the dependency of gevent=1.4.0 cannot be installed. Can I use gevent=22.10.2 instead?

**Comment by Avey777** [comment]
Python 3.7 is too old for us as many dependencies cannot be used with Python 3.7.x.

**Comment by gaecoli** [comment]
> 

Python 3.9, you can install `gevent==1.3.4`, if you can't run it, you can add `greenlet==0.4.17`. I tested it, it works.

**Comment by justinclift** [comment]
Make a PR with it?

If it gets through the CI fine, then we can merge it.

Btw - there are 4 outstanding existing PR's in the repo, created by dependabot.  Those four seem to be non-trivial to upgrade though and I don't have much spare time this week.  If someone else can take a look at them, that would be awesome. :smile:

**Comment by Avey777** [comment]
> > 
> 
> Python 3.9, you can install , if you can't run it, you can add . I tested it, it works.`gevent==1.3.4``greenlet==0.4.17`

` Rolling back uninstall of gevent
  Moving to /usr/local/lib/python3.9/dist-packages/gevent-22.10.2.dist-info/
   from /usr/local/lib/python3.9/dist-packages/~event-22.10.2.dist-info
  Moving to /usr/local/lib/python3.9/dist-packages/gevent/
   from /usr/local/lib/python3.9/dist-packages/~event
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w4dbemnq/gevent_c5b4074345d34c5f9286fac00114a361/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w4dbemnq/gevent_c5b4074345d34c5f9286fac00114a361/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sehr8liw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/gevent Check the logs for full command output.`

After modifying the two dependency versions mentioned above, I am still unable to install gevent properly.

**Comment by gaecoli** [comment]
gevent                22.8.0
greenlet              1.1.3

**Comment by gaecoli** [comment]
> gevent 22.8.0 greenlet 1.1.3

@Avey777 You can test it.

**Comment by Avey777** [comment]
> gevent 22.8.0 greenlet 1.1.3

Great!

Currently, there is no documentation on the dependencies for different versions. It would be great to have documentation on dependencies for different major Python versions in the future. 

Also, Debian now comes with Python 3.9 installed by default.

**Comment by gaecoli** [comment]
> > gevent 22.8.0 greenlet 1.1.3
> 
> Great!
> 
> Currently, there is no documentation on the dependencies for different versions. It would be great to have documentation on dependencies for different major Python versions in the future.
> 
> Also, Debian now comes with Python 3.9 installed by default.

Lately, i will add this info.

**Comment by gaecoli** [comment]
> @gaecoli Has this been done? I'm not seeing anything in our Docker Hub repo, nor wiki page with info, etc.
> 
> Am I looking in the wrong place? 😄

Sorry, I edit wiki page, but not push. I reopen this issue.

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by gaecoli** [comment]
@justinclift How can i push my new docker image to our docker hub?

**Comment by Avey777** [comment]
> No worries at all. 😄

Looking forward to the release of our community edition's first Redash image as soon as possible.

**Comment by justinclift** [comment]
@gaecoli With this new docker image, is it a stable release build, or is it built from our our current master branch (aka "a development build"), or is it something else?

Just so we know how to talk about it, as our potential users will definitely want to know. :smile:

**Comment by hazmeister** [comment]
@justinclift secrets should be in github, I haven't had a chance to look at changing build number info yet, so we might want that before merging?

I think for releases we'll want a manual action trigger from a specific branch, which will come in a later PR.

https://github.com/RedashCommunity/redash/pull/25

**Comment by justinclift** [comment]
Good stuff with that PR @hazmeister. :smile:

Looking at the build number info in `master` at the moment, it's currently saying `11.0.0-dev` which seems fine for prerelease things.  So, I've just reviewed and merged the PR.

Any idea if the PR merge itself will generate a preview docker build, or if it'll start happening with the next merge, or ?

**Comment by justinclift** [comment]
k, well this sounds like the preview docker builds should be about under control now, so that's good progress.

Next step will be to get updated, secure "release" builds done.

@hazmeister and @gaecoli You both seem to be working on that bit, but separately yeah?  If that's the case, would it be useful to work together on it or something?

**Comment by hazmeister** [comment]
Still getting used to GitHub Actions.  Referencing the environment allowed reading the secrets in.  We now have a preview image. I'll look at manual actions for the release branches later this week.

**Comment by justinclift** [comment]
Awesome!

Ironically, the [Cypress](https://www.cypress.io) tests didn't pass this time around, but that's probably just a false positive.  Having used Cypress before with a different project, it was flaky there too.

So, am re-running that failed job now and (in theory) it should pass a 2nd time around.  Or maybe 3rd, we'll see. :wink:

But, working preview image now, that's excellent! :smile:

**Comment by justinclift** [comment]
Cool, the re-run of the failed job worked first time around. :smile:

@hazmeister Would it makes sense to have the upload of the preview build (to Docker Hub) only happen after the CI tests successfully pass?

Am kind of thinking that uploading a build that fails CI is probably not what we want.

Looking at the existing ci.yml file, ordering seems to be done using the `needs` line.  eg:

* https://github.com/RedashCommunity/redash/blob/bb1d45ba3e1690a8acef192935916c2d6e5476d4/.github/workflows/ci.yml#L24
* https://github.com/RedashCommunity/redash/blob/bb1d45ba3e1690a8acef192935916c2d6e5476d4/.github/workflows/ci.yml#L10-L20

No idea if they can cross-reference things in other .yml files, or if we need to move the contents of docker-preview.yml into ci.yml, etc.

Thoughts? :smile:

**Comment by Avey777** [comment]
```
version: "2"
x-redash-service: &redash-service
  image: redashcommunity/redash:preview
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5500:5000"
    environment:
      REDASH_WEB_WORKERS: 4

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  redis:
    image: redis:5.0-alpine
    container_name: redash-redis
    restart: always

  postgres:
    image: postgres:9.6-alpine
    container_name: redash-postgres
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
```
Can I install Redash like this? Should I write the .env file in the docker-compose.yml or do I need to create a separate .env file?

**Comment by gaecoli** [comment]
> ```
> version: "2"
> x-redash-service: &redash-service
>   image: redashcommunity/redash:preview
>   depends_on:
>     - postgres
>     - redis
>   env_file: /opt/redash/env
>   restart: always
> 
> services:
>   server:
>     <<: *redash-service
>     command: server
>     ports:
>       - "5500:5000"
>     environment:
>       REDASH_WEB_WORKERS: 4
> 
>   scheduler:
>     <<: *redash-service
>     command: scheduler
>     environment:
>       QUEUES: "celery"
>       WORKERS_COUNT: 1
> 
>   scheduled_worker:
>     <<: *redash-service
>     command: worker
>     environment:
>       QUEUES: "scheduled_queries,schemas"
>       WORKERS_COUNT: 1
> 
>   adhoc_worker:
>     <<: *redash-service
>     command: worker
>     environment:
>       QUEUES: "queries"
>       WORKERS_COUNT: 2
> 
>   redis:
>     image: redis:5.0-alpine
>     container_name: redash-redis
>     restart: always
> 
>   postgres:
>     image: postgres:9.6-alpine
>     container_name: redash-postgres
>     env_file: /opt/redash/env
>     volumes:
>       - /opt/redash/postgres-data:/var/lib/postgresql/data
>     ports:
>       - "5432:5432"
>     restart: always
> ```
> 
> Can I install Redash like this? Should I write the .env file in the docker-compose.yml or do I need to create a separate .env file?


It is not necessary to create a .env file separately. But it is recommended that you separate the redis service and postgres service from docker and deploy them on the machine separately, so that there is no risk of data loss.

**Comment by Avey777** [comment]
```
x-redash-environment:` &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_GUNICORN_TIMEOUT: 60
  # Set secret keys in the .env file
  ```

**Comment by Avey777** [comment]
```
x-redash-environment:` &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_GUNICORN_TIMEOUT: 60
  # Set secret keys in the .env file
  ```
  
  Do I not need to add the above information to the docker-compose.yml file? Following the above steps did not result in a successful deployment.

**Comment by justinclift** [comment]
> ... deploy them on the machine separately, so that there is no risk of data loss.

That's not the full picture.
With the PostgreSQL service part... :

```
  postgres:
    image: postgres:9.6-alpine
    container_name: redash-postgres
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
```

... the `volume` line there is important:

```
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
```

That tells Docker to actually store the PostgreSQL database files on the host, rather than inside the container.  So if you destroy and rebuild the container, then the database doesn't get destroyed at the same time.

That being said, you should have some kind of backup of the database happening anyway, just in case the whole host system dies for some reason.
